# Generated by Django 2.0 on 2018-01-11 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=80)),
                ('song_language', models.CharField(max_length=80)),
                ('song_type', models.CharField(max_length=80)),
                ('song_pinyin', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_name', models.CharField(max_length=30)),
                ('star_sex', models.CharField(max_length=30)),
                ('star_country', models.CharField(max_length=30)),
                ('star_type', models.CharField(max_length=30)),
                ('star_pinyin', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='song_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='songs.star'),
        ),
    ]
